### ISSUE TITLE
Feature Request: proper/different Object key color in JavaScript

### ISSUE THREAD

**Issue by timidak** [kevinvn1709/vscode-dracula-color-theme#1]
**Story:**  As a User I want to see a different color for Object-Keys in JavaScript than that as for Object-String-Values.
In the IntelliJ-Darcula-Theme these Object-Keys are colored `purple`.

| Screenshot IntelliJ        | this Theme           |
| :-------------:|:-------------:|
| <img width="352" alt="bildschirmfoto 2018-12-17 um 11 38 37" src="https://user-images.githubusercontent.com/18395108/50082873-51f16a00-01f2-11e9-89f7-c72b00fbd40a.png"> | ![bildschirmfoto 2018-12-17 um 11 38 45](https://user-images.githubusercontent.com/18395108/50083032-ccba8500-01f2-11e9-9d0c-d6505f070eba.png) |

Is this possible to implement?
If you give me a short introduction I would try it myself.

**Comment by timidak** [comment]
Notify @kevinvn1709 🙈

**Comment by kevinvn1709** [comment]
Sorry @timidak for late response. 
But I have not got problem like you. This is theme color from my side.
 
![image](https://user-images.githubusercontent.com/1281425/50881925-bc728000-1415-11e9-9258-f8150117c6af.png)

It seems like you are not enable my theme. You can check it out again.

:Preferences > Color Theme > Darcula Theme from IntelliJ

![image](https://user-images.githubusercontent.com/1281425/50882006-0491a280-1416-11e9-9352-70da8c6f9d2b.png)

And, I will close it for now. you could open another issues if you got any problems with it.
